// <auto-generated />
using System;
using BusPass.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusPass.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200831132342_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("BusPass.Shared.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(21);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BusPass.Shared.Entities.BusPassPayment", b =>
                {
                    b.Property<int>("BusPassPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusPassportId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfPayment")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonthId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("price")
                        .HasColumnType("REAL");

                    b.HasKey("BusPassPaymentId");

                    b.HasIndex("BusPassportId");

                    b.HasIndex("MonthId");

                    b.ToTable("BusPassPayments");
                });

            modelBuilder.Entity("BusPass.Shared.Entities.BusPassport", b =>
                {
                    b.Property<int>("BusPassportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("TEXT");

                    b.Property<int>("PassTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Valid")
                        .HasColumnType("INTEGER");

                    b.HasKey("BusPassportId");

                    b.HasIndex("PassTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("BusPassports");
                });

            modelBuilder.Entity("BusPass.Shared.Entities.Month", b =>
                {
                    b.Property<int>("MonthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MonthId");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("BusPass.Shared.Entities.PassType", b =>
                {
                    b.Property<int>("PassTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("PassTypeId");

                    b.ToTable("PassTypes");
                });

            modelBuilder.Entity("BusPass.Shared.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(11);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusPass.Shared.Entities.Account", b =>
                {
                    b.HasOne("BusPass.Shared.Entities.User", null)
                        .WithOne("Account")
                        .HasForeignKey("BusPass.Shared.Entities.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusPass.Shared.Entities.BusPassPayment", b =>
                {
                    b.HasOne("BusPass.Shared.Entities.BusPassport", "BusPass")
                        .WithMany("BusPassPayments")
                        .HasForeignKey("BusPassportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusPass.Shared.Entities.Month", "Month")
                        .WithMany("BusPassPayments")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusPass.Shared.Entities.BusPassport", b =>
                {
                    b.HasOne("BusPass.Shared.Entities.PassType", "PassType")
                        .WithMany("BusPassports")
                        .HasForeignKey("PassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusPass.Shared.Entities.User", "User")
                        .WithMany("BusPassports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
